### ISSUE TITLE
Bottom bar position not fixed.

### ISSUE THREAD

**Issue by Sutanshu** [CMPUT301F20T32/BookIt#61]
Bottom bar rises with the keyboard, ideally this shouldn't happen.
<img width="313" alt="Screen Shot 2020-11-05 at 9 32 59 PM" src="https://user-images.githubusercontent.com/42788023/98326428-7b663b00-1fae-11eb-95a7-e9e4e9b5a62f.png">

**Comment by nluu175** [comment]
Done!
